

POST http://localhost:8000/api/transactions HTTP/1.1
content-type: application/json

{
  "time": "14:45",
  "hm": "1010",
  "vol": "200",
  "initial_flow": "1200",
  "final_flow": "1400",
  "driver": "Mr Bis",
  "location": "PIT GRIYA",
  "user_id": 2,
  "unit_id": 3
}


###

GET http://localhost:8000/api/transactions HTTP/1.1

###

POST http://localhost:8000/api/login HTTP/1.1
content-type: application/json

{
    "email": "fm@gmail.com",
    "password": "admin123"
}

###

POST http://localhost:8000/api/logout HTTP/1.1
Authorization: Bearer 22|Z2OJVlsP3f8HgXWrI5fqYKcqmE88GZug8Mvq0pxXe3edb34c
Accept: application/json


###
GET http://localhost:8000/api/units/HBP102


###
GET http://localhost:8000/api/user
