

POST http://localhost:8000/api/transactions HTTP/1.1
content-type: application/json

{
  "time": "14:45",
  "hm": "1010",
  "vol": "200",
  "initial_flow": "1200",
  "final_flow": "1400",
  "driver": "Mr Bis",
  "location": "PIT GRIYA",
  "user_id": 2,
  "unit_id": 3
}


###

GET http://localhost:8000/api/transactions HTTP/1.1

###

POST http://localhost:8000/api/login HTTP/1.1
content-type: application/json

{
    "email": "admin@gmail.com",
    "password": "admin123"
}

###

POST http://localhost:8000/api/logout HTTP/1.1
Authorization: Bearer 2|65ux1nyQvoJRX5vr1onCl4UPTLbbo1LYlM7Z5sIE0fe52664
Accept: application/json


###
GET http://localhost:8000/api/units/HBP102
